name: "Daily Package Sync Checker"

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight UTC
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write # This gives the workflow permission to push to the repository

jobs:
  check-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for proper commit messages
          token: ${{ secrets.GH_PAT }} # Use PAT for checkout to ensure push access

      - name: Debug Git setup
        run: |
          echo "Current user: $(git config user.name)"
          echo "Current email: $(git config user.email)"
          echo "Remote URL: $(git remote -v)"
          echo "Current branch: $(git branch --show-current)"
          echo "GitHub Actor: ${{ github.actor }}"
          echo "GitHub Repository: ${{ github.repository }}"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install requests toml

      - name: Run daily check script
        run: |
          python scripts/daily_check.py
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
